"use client"

import Link from "next/link"
import Image from "next/image"
import { useEffect, useState } from "react"
import type { DerivedMetrics, MicrogridReading } from "@/lib/types"
import { WallClock } from "./wall-clock"
import { LiveTicker } from "./live-ticker"
import { AmbientSparkline } from "./ambient-sparkline"

interface AmbientViewProps {
  metrics: DerivedMetrics
  readings: MicrogridReading[]
  isLive: boolean
}

interface Story {
  eyebrow: string
  figure: string
  unit: string
  caption: string
  footnote: string
  accent: string
  sparkKey: keyof MicrogridReading
  sparkVariant: "area" | "line"
}

const STORY_MS = 9000

export function AmbientView({ metrics, readings, isLive }: AmbientViewProps) {
  const latest = readings[readings.length - 1] ?? null

  const stories: Story[] = [
    {
      eyebrow: "solar, today",
      figure: metrics.solarEnergyKwh.toFixed(1),
      unit: "kWh",
      caption: "generated by the rooftop panels since midnight",
      footnote: "Σ PVpow × (1/60) / 1000",
      accent: "var(--solar)",
      sparkKey: "PVpow",
      sparkVariant: "area",
    },
    {
      eyebrow: "co₂ avoided",
      figure: metrics.co2AvoidedKg.toFixed(1),
      unit: "kg",
      caption: "not emitted into the atmosphere today",
      footnote: "EPA eGRID US average — 0.386 kg/kWh",
      accent: "#059669",
      sparkKey: "PVpow",
      sparkVariant: "area",
    },
    {
      eyebrow: "battery",
      figure: metrics.currentBatteryVoltage.toFixed(1),
      unit: "V",
      caption: `currently ${metrics.batteryStatus.toLowerCase()}`,
      footnote: "direction from BattCurr ±0.5 A threshold",
      accent: "var(--battery)",
      sparkKey: "BattPow",
      sparkVariant: "area",
    },
    {
      eyebrow: "live right now",
      figure: metrics.currentSolarPower.toFixed(0),
      unit: "W",
      caption: metrics.systemOnline
        ? "of solar power flowing through the microgrid"
        : "the system is idle",
      footnote: "latest 1-minute PVpow reading",
      accent: "var(--solar)",
      sparkKey: "PVpow",
      sparkVariant: "area",
    },
  ]

  const [index, setIndex] = useState(0)
  const [tick, setTick] = useState(0) // increments to restart the CSS animation

  useEffect(() => {
    const id = setInterval(() => {
      setIndex((i) => (i + 1) % stories.length)
      setTick((t) => t + 1)
    }, STORY_MS)
    return () => clearInterval(id)
  }, [stories.length])

  function goTo(i: number) {
    setIndex(i)
    setTick((t) => t + 1)
  }

  const story = stories[index]

  return (
    <section
      aria-label="Campus microgrid at a glance"
      className="relative flex min-h-[100dvh] flex-col overflow-hidden bg-white text-foreground"
    >
      {/* Subtle colorful gradient background */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(60% 50% at 20% 30%, rgba(224,160,48,0.10) 0%, transparent 60%), radial-gradient(55% 55% at 80% 75%, rgba(45,63,160,0.09) 0%, transparent 65%), radial-gradient(40% 40% at 55% 50%, rgba(200,16,46,0.06) 0%, transparent 70%)",
        }}
      />

      {/* Top bar */}
      <header className="relative z-20 flex items-center justify-between bg-clark-red px-5 py-4 sm:px-10 sm:py-5">
        <div className="flex items-center gap-3">
          <Image
            src="/clark.png"
            alt="Clark University"
            width={32}
            height={32}
            className="rounded-full ring-1 ring-white/30"
          />
          <div className="leading-tight">
            <p className="font-serif-display text-2xl font-semibold text-white">CURED</p>
            <p className="small-caps text-[10px] font-medium text-white/85 sm:text-[11px]">
              Clark Renewable Energy Dashboard
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3 sm:gap-5">
          <span className="inline-flex items-center gap-1.5">
            <span
              className={`inline-block h-1.5 w-1.5 rounded-full ${
                isLive ? "bg-emerald-300 live-dot" : "bg-amber-300"
              }`}
            />
            <span className="small-caps text-[10px] text-white/80">
              {isLive ? "live" : "no data"}
            </span>
          </span>
          <WallClock />
        </div>
      </header>

      {/* Hero story */}
      <main className="relative z-10 flex flex-1 items-center justify-center px-5 py-10 sm:px-10">
        <div
          key={index}
          className="rise-in relative grid w-full max-w-6xl grid-cols-1 items-end gap-10 lg:grid-cols-[1.3fr_1fr] lg:gap-14"
        >
          {/* Left: numeral + caption */}
          <div className="flex flex-col items-start">
            <p
              className="small-caps mb-4 text-[clamp(0.7rem,1.3vw,0.9rem)] sm:mb-6"
              style={{ color: story.accent }}
            >
              {story.eyebrow}
            </p>

            <div className="flex items-baseline gap-4 sm:gap-6">
              <span
                className="font-serif-display text-ink"
                style={{ fontSize: "clamp(6rem, 26vw, 22rem)" }}
              >
                {story.figure}
              </span>
              <span className="font-serif-display text-foreground/50 text-[clamp(2rem,5vw,4.5rem)]">
                {story.unit}
              </span>
            </div>

            <p className="mt-4 max-w-2xl text-[clamp(1rem,1.8vw,1.5rem)] leading-snug text-foreground/70 sm:mt-6">
              {story.caption}
            </p>

            <p className="small-caps mt-4 font-mono text-[12px] text-foreground/55 sm:mt-6 sm:text-[13px]">
              {story.footnote}
            </p>

            <div className="mt-8 flex items-center gap-3 sm:mt-10">
              {stories.map((s, i) => (
                <button
                  key={i}
                  type="button"
                  onClick={() => goTo(i)}
                  aria-label={s.eyebrow}
                  className="group flex flex-col items-start px-0 py-3 focus:outline-none"
                >
                  {/* Track */}
                  <div className="relative h-[3px] w-14 overflow-hidden bg-foreground/12 rounded-full">
                    {i === index && (
                      <div
                        key={tick}
                        className="absolute inset-y-0 left-0 bg-foreground rounded-full"
                        style={{
                          animation: `story-progress ${STORY_MS}ms linear forwards`,
                        }}
                      />
                    )}
                    {i < index && (
                      <div className="absolute inset-0 bg-foreground/40 rounded-full" />
                    )}
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Right: sparkline */}
          <div className="flex flex-col border-l border-rule/10 pl-6 lg:pl-10">
            <p className="small-caps text-[10px] text-muted-foreground sm:text-[11px]">
              shape of the day
            </p>
            <div className="mt-3">
              <AmbientSparkline
                data={readings}
                dataKey={story.sparkKey}
                color={story.accent}
                variant={story.sparkVariant}
                height={220}
              />
            </div>
            <div className="mt-3 flex justify-between font-mono text-[10px] text-muted-foreground/60">
              <span>00:00</span>
              <span>12:00</span>
              <span>24:00</span>
            </div>
          </div>
        </div>
      </main>

      {/* Telemetry ticker */}
      <LiveTicker latest={latest} />

      {/* Bottom tray */}
      <div className="relative z-10 flex items-center justify-between border-t border-rule/10 px-5 py-3 sm:px-10">
        <p className="small-caps font-mono text-[12px] text-foreground/60">
          PHYS 243 / 343 · Prof. Agosta
        </p>
        <div className="flex items-center gap-4 sm:gap-6">
          <Link
            href="/research"
            className="small-caps inline-flex items-center gap-2 text-[13px] font-medium text-foreground/70 transition-colors hover:text-foreground"
          >
            Research view →
          </Link>
          <a
            href="#learn"
            className="small-caps hidden items-center gap-2 text-[13px] font-medium text-foreground/70 transition-colors hover:text-foreground sm:inline-flex"
          >
            Scroll for more ↓
          </a>
        </div>
      </div>
    </section>
  )
}
